// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdWWayzf1fK3TXyJUF8c_heysD6PtgLg',
    appId: '1:100947889363:web:7c27c15393d140d0d5d826',
    messagingSenderId: '100947889363',
    projectId: 'chatgpt-otp-bot',
    authDomain: 'chatgpt-otp-bot.firebaseapp.com',
    storageBucket: 'chatgpt-otp-bot.firebasestorage.app',
    measurementId: 'G-RHZFE187F0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxc-HBsJdMNjL6_PX4oW41waXo6BstGNE',
    appId: '1:100947889363:ios:6ac6ba33031e67f6d5d826',
    messagingSenderId: '100947889363',
    projectId: 'chatgpt-otp-bot',
    storageBucket: 'chatgpt-otp-bot.firebasestorage.app',
    iosBundleId: 'com.example.studentAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxc-HBsJdMNjL6_PX4oW41waXo6BstGNE',
    appId: '1:100947889363:ios:6ac6ba33031e67f6d5d826',
    messagingSenderId: '100947889363',
    projectId: 'chatgpt-otp-bot',
    storageBucket: 'chatgpt-otp-bot.firebasestorage.app',
    iosBundleId: 'com.example.studentAdminApp',
  );
}
